### ISSUE TITLE
Found bug in msr-tools 1.2

### ISSUE THREAD

**Issue by pautee** [01org/msr-tools#1] opened 2013-09-26 23:20 UTC
Unable to write to upper 32 bits of msr. Lower 32 bits are getting written properly

**Comment by jinksong** [comment] 2013-09-27 02:50
Is there any possibility that those MSR's support lower 32 bits only?

**Comment by jinksong** [comment] 2013-10-01 19:59
This issue is identified as a problem in Red Hat 'msr-tools' package. I will follow up this issue with Red Hat as they need to update to version 1.3 anyhow and the project is moved to 01.org now.

**Comment by jinksong** [comment] 2013-10-04 02:46
Opened a bug item in
https://bugzilla.redhat.com/show_bug.cgi?id=1015356

**Comment by jinksong** [comment] 2013-10-07 17:23
Since the problem is originated from openSUSE package, it is filed to openSUSE again.
https://bugzilla.novell.com/show_bug.cgi?id=844336

**Comment by gebailey** [comment] 2014-09-24 05:52
I don't have permissions to see https://bugzilla.redhat.com/show_bug.cgi?id=1015356 but I've just submitted updates for Fedora and EPEL (RedHat/CentOS) repos to update to version 1.3.  They'll be in a testing repository for a week or so before landing in stable repositories.

**Comment by mirh** [comment] 2017-02-21 20:57
Can be closed then?

**Comment by gebailey** [comment] 2017-02-21 23:35
All of the Fedora and EPEL (RedHat/CentOS) branches are using version 1.3.  I can't speak to what openSUSE is packaging.

**Comment by mirh** [comment] 2017-02-22 01:10
They are [too](https://build.opensuse.org/request/show/208543).

**Comment by jinksong** [comment] 2017-03-20 20:35
Closing. Thanks for the confirmation!

**Closed as completed by jinksong** 2017-03-20 20:35 UTC
